version: "3.7"

# Docker environment
services:
  
  ####### Service for Python functions ######
  pythonfunctions:
    
    build: ./pythonfunctions/
      context: ./vs_code_directory/Projects/test_thanks_alatte  
      dockerfile: Dockerfile 
    
    command: python ./mysqlconnector.py
    
    depends_on:
      - mysql
      - postgres
    
    networks:
      - ProjectNetwork

  ####### Service for MySQL database ######
  services:
  mysql:
    
    build:
      context: ./mysql  
      dockerfile: Dockerfile  
    
    container_name: mysql_container
    
    restart: always
    
    environment:
      MYSQL_DATABASE: thanks_alatte
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    
    ports:
      - '3306:3306'  
    
    volumes:
      - mysql_data:
    
    networks:
      - ProjectNetwork


  ####### Service for PostgreSQL database ######
  postgres:
  
    image: postgres:latest
    
    environment:
      POSTGRES_DB: thanks_alatte
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      ports:
        - '3306:3306'
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    networks:
      - ProjectNetwork

  ####### Service for Adminer (Database management tool) ######
  adminer:
    
    image: adminer
    
    container_name: adminer_container
    
    restart: always
    
    ports:
      - 8080:8080
    
    networks:
      - ProjectNetwork


networks:
  ProjectNetwork:


volumes:
  mysql_data:
  postgres_data:
